Revert "python3 build requires python2 version of 2to3"
This reverts commit e7910477aedc81c613a340e40f768607947fd5eb.

pylint build will fail without python3-2to3:

>  File "/usr/share/python3.3/distutils/util.py", line 507, in run_2to3
>    from lib2to3.refactor import RefactoringTool, get_fixers_from_package
> ImportError: No module named 'lib2to3'
> error: Bad exit status from /home/users/jacek/tmp/rpm-tmp.73470 (%build)

pylint builds with python3-2to3 and without python-2to3 installed.

Buggy version of python3-distribute was in use?